### ISSUE TITLE
use variables in baseURL

### ISSUE THREAD

**Issue by Dzibeul** [anttiviljami/openapi-client-axios#20]
Hi,

I use a OpenAPI file with variables in servers url  : 

```
servers:
 url: https://api.{region}.domain.com/api/v1
  variables:
    region:
      default: eu-west-2
      enum: [eu-west-2, us-east-2, us-west-1]
 url: https://api.{region}.domain.hk/api/v1
  variables:
    region:
      default: cn-southeast-1
      enum: [cn-southeast-1]

```

When I use the getBaseURL() function, it returns this :   

https://api.{region}.domain.com/api/v1

Is there a way to pass parameters in order to build the baseURL with the {region}, or at least the default value?

Thanks
