### ISSUE TITLE
Add support for other parameter types (query, header, cookie ...)

### ISSUE THREAD

**Issue by Omicron7** [anttiviljami/openapi-client-axios#5]
The OpenAPIv3 spec supports [describing](https://swagger.io/docs/specification/describing-parameters/) other types of parameters including query and header.

I have an openapi v3 spec that includes some of these. I'd love to be able to pass them directly in the pathParams and have the client automatically serialize them according to the spec.

Example:
```yaml
paths:
  /systems:
    get:
      summary: List all Systems
      operationId: getSystems
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
            default: 300
        - name: offset
          in: query
          schema:
            type: integer
            format: int32
  /entity_types:
    get:
      summary: List all Entity Types
      operationId: getEntityTypes
      parameters:
        - name: filters
          in: query
          style: deepObject
          explode: true
          schema:
            type: object
            properties:
              parent_id:
                type: string
                format: uuid
              data_visibility:
                type: string
                enum: [public, private, shared_ownership]
```
`client.getSystems({limit: 10})` results in `GET /systems?limit=10`

`client.getEntityTypes({filters: {data_visibility: 'public'}})` results in `GET /entity_types?filters[data_visibility]=public`

We currently need to manually create an AxiosRequestConfig for every request that includes parameters that are not path parameters.
